### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by rodrigovcortezi** [rodrigovcortezi/INF1771#1]
Fala ai galera, beleza? Então... a gente só tem **duas semanas** pra fazer esse trabalho. Seria uma boa já começarmos a planejar o que vamos fazer e quem vai fazer o que. 

Precisamos:

- Escolher o problema entre os dois propostos no enunciado. 
- Decidir quais serão os dois algoritmos de buscas a implementar. 
- Dividir o trabalho em partes para que cada um fique responsável em uma parte. 

O que vocês acham?

Partiu fazer bonito em :)

**Comment by rodrigovcortezi** [comment]
Sobre qual dos problemas escolher, por mim tanto faz. Mas acho que voto no caixeiro em..

**Comment by danirlcr10** [comment]
Eu curto a ideia do caixeiro também hein
